
### Get all comments
GET http://localhost:3000/api/comments

### Get replies of a comment (use id from your database)
GET http://localhost:3000/api/comments/:0f893bac-627c-43f7-b55e-ee074e1d32f9

### Post a comment 
POST http://localhost:3000/api/comments
Content-Type: application/json

{
    "commentText": "TEST",
    "date": "2024-10-22T22:30:00Z",
    "likes": 100,
    "dislikes": 1000,
}

### Post a comment with a parent id (use id from your database)
POST http://localhost:3000/api/comments
Content-Type: application/json

{
    "commentText": "HERE IS A TEST OF A NEW ENDPOINT",
    "date": "2024-10-22T22:30:00Z",
    "likes": 100,
    "dislikes": 1000,
    "parentId": "0f893bac-627c-43f7-b55e-ee074e1d32f9", 
    "email": "test_user@test.com",
    "username": "test_user"
}
